# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbdb78280e5da749ad6a46effe2f97488d8066dc864334429e7bbbf0e069951c10fdf20d53035abec3c592937fa4b12e478c2e824727211389882bad790c2b3c

test:
  secret_key_base: 1bde4c6940ae1bc4233acdbbcfbf09966252d9166b63d74fb505264090654f323f89cf07be23ddc35d2d24d0e7875cde855aa711531feba2842424b98ef7924d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
